[package]
name = "dayder"
version = "0.1.0"
authors = ["Marc Mailhot <mmm11105@gmail.com>"]

[dependencies]
byteorder = "0.5.1"
iron = "0.3.0"
staticfile = "0.2.0"
mount = "0.1.0"
persistent = "0.1.0"
lru_time_cache = "0.2.7"
lazy_static = "0.1.*"
url = "0.5.7"
